# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymess', '0007_auto_20190401_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialertemplate',
            name='is_allowed_duplicate_messages',
            field=models.BooleanField(default=True, verbose_name='Duplicate messages are allowed'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_allowed_duplicate_messages',
            field=models.BooleanField(default=True, verbose_name='Duplicate messages are allowed'),
        ),
        migrations.AddField(
            model_name='pushnotificationtemplate',
            name='is_allowed_duplicate_messages',
            field=models.BooleanField(default=True, verbose_name='Duplicate messages are allowed'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='is_allowed_duplicate_messages',
            field=models.BooleanField(default=True, verbose_name='Duplicate messages are allowed'),
        ),
    ]
