# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-10 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pymess', '0014_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialermessage',
            name='state',
            field=models.IntegerField(
                choices=[(0, 'not assigned'), (1, 'ready'), (2, 'rescheduled by dialer'), (3, 'call in progress'),
                         (4, 'hangup'), (5, 'done'), (6, 'rescheduled'), (7, 'listened up complete message'),
                         (8, 'listened up partial message'), (9, 'unreachable'), (10, 'declined'), (11, 'unanswered'),
                         (12, 'unanswered - hangup by dialer'), (13, 'answered - hangup by customer'), (66, 'error'),
                         (77, 'debug')], editable=False, verbose_name='state'),
        ),
    ]
